import type { Locale } from "@/lib/i18n/config";

export const siteText = {
  de: {
    hero: { kickerHome: "ZVG-DE.COM · GERICHTLICHE VERSTEIGERUNGEN", kickerMap: "KARTE · DEUTSCHLANDWEIT SUCHEN", homeTitle: "Alle gerichtlichen Versteigerungen an einem Ort.", homeSubtitle: "Transparent. Verlässlich. Übersichtlich. Finden Sie Immobilien, Grundstücke und weitere Objekte aus gerichtlichen Versteigerungen mit Karte, Filtern und strukturierten Informationen.", mapTitle: "Gerichtliche Versteigerungen auf der Karte finden", mapSubtitle: "Suchen Sie nach Regionen, Gerichten, Preisen und Objektarten. Die Karte unterstützt Gebietssuche und Polygon-Auswahl.", checkedSources: "Geprüfte Quellen", dailyUpdated: "Täglich aktualisiert", nationwide: "Deutschlandweit", objectsInDatabase: "Immobilien in der Datenbank", objectsOnMap: "auf der Karte", averageMarketValue: "Ø Verkehrswert", freeSearch: "kostenlos suchen", federalStates: "Bundesländer" },
    quickSearch: { title: "Schnellsuche", subtitle: "Starten Sie mit den wichtigsten Kriterien. Die vollständige Suche finden Sie auf der Kartenseite.", queryLabel: "Ort, PLZ, Adresse oder Gericht", queryPlaceholder: "z. B. Chemnitz, 09111, Amtsgericht Dresden", federalState: "Bundesland", allStates: "Alle Bundesländer", propertyType: "Objektart", allTypes: "Alle Typen", maxValue: "Verkehrswert bis", any: "Beliebig", quickButton: "Schnell suchen", advancedButton: "Erweiterte Suche" },
    map: { sectionTitle: "Versteigerungen auf der Karte", sectionText: "Ein schneller Überblick. Die große Karte mit allen Filtern finden Sie im Bereich Karte.", openLargeMap: "Große Karte öffnen", title: "Karte der Objekte", subtitle: "Suchen Sie in der sichtbaren Kartenfläche oder zeichnen Sie eine eigene Suchregion.", searchArea: "In diesem Kartenausschnitt suchen", drawRegion: "Region zeichnen", page: "Seite", found: "Gefunden", active: "Aktiv", cancelled: "Aufgehoben", archive: "Archiv", maxValue: "Max. Wert" },
    list: { title: "Top 12 aktuelle Objekte", subtitle: "Kurze Auswahl für die Startseite. Die vollständige Recherche finden Sie in der erweiterten Suche.", advancedLink: "Zur erweiterten Suche", shown: "Gezeigt", of: "von", previous: "Zurück", next: "Weiter" },
    footer: { about: "Über uns", privacy: "Datenschutz" }
  },
  ru: {
    hero: { kickerHome: "ZVG-DE.COM · СУДЕБНЫЕ АУКЦИОНЫ", kickerMap: "КАРТА · ПОИСК ПО ВСЕЙ ГЕРМАНИИ", homeTitle: "Все судебные аукционы в одном месте.", homeSubtitle: "Прозрачно. Надёжно. Удобно. Находите недвижимость, участки и другие объекты судебных торгов с картой, фильтрами и структурированной информацией.", mapTitle: "Поиск судебных аукционов на карте", mapSubtitle: "Ищите по регионам, судам, ценам и типам объектов. Карта поддерживает поиск по области и выделение полигона.", checkedSources: "Проверенные источники", dailyUpdated: "Ежедневное обновление", nationwide: "По всей Германии", objectsInDatabase: "объектов в базе", objectsOnMap: "на карте", averageMarketValue: "Ø оценочная стоимость", freeSearch: "бесплатный поиск", federalStates: "федеральных земель" },
    quickSearch: { title: "Быстрый поиск", subtitle: "Начните с основных критериев. Полный поиск доступен на странице расширенного поиска.", queryLabel: "Город, индекс, адрес или суд", queryPlaceholder: "например: Chemnitz, 09111, Amtsgericht Dresden", federalState: "Федеральная земля", allStates: "Все земли", propertyType: "Тип объекта", allTypes: "Все типы", maxValue: "Оценочная стоимость до", any: "Любая", quickButton: "Быстрый поиск", advancedButton: "Расширенный поиск" },
    map: { sectionTitle: "Аукционы на карте", sectionText: "Краткий обзор. Большая карта со всеми фильтрами находится в разделе Карта.", openLargeMap: "Открыть большую карту", title: "Карта объектов", subtitle: "Ищите в видимой области карты или нарисуйте собственную область поиска.", searchArea: "Искать в этой области карты", drawRegion: "Нарисовать область", page: "Страница", found: "Найдено", active: "Активно", cancelled: "Отменено", archive: "Архив", maxValue: "Макс. стоимость" },
    list: { title: "Топ-12 актуальных объектов", subtitle: "Короткая подборка для главной страницы. Полный поиск доступен в расширенном поиске.", advancedLink: "К расширенному поиску", shown: "Показано", of: "из", previous: "Назад", next: "Вперёд" },
    footer: { about: "О проекте", privacy: "Конфиденциальность" }
  },
  en: {
    hero: { kickerHome: "ZVG-DE.COM · JUDICIAL AUCTIONS", kickerMap: "MAP · SEARCH ACROSS GERMANY", homeTitle: "All judicial auctions in one place.", homeSubtitle: "Transparent. Reliable. Clear. Find real estate, land and other judicial auction properties with maps, filters and structured information.", mapTitle: "Find judicial auctions on the map", mapSubtitle: "Search by region, court, price and property type. The map supports area search and polygon selection.", checkedSources: "Verified sources", dailyUpdated: "Updated daily", nationwide: "Germany-wide", objectsInDatabase: "properties in database", objectsOnMap: "on the map", averageMarketValue: "Ø market value", freeSearch: "free search", federalStates: "federal states" },
    quickSearch: { title: "Quick Search", subtitle: "Start with the most important criteria. Full search is available on the advanced search page.", queryLabel: "City, ZIP, address or court", queryPlaceholder: "e.g. Chemnitz, 09111, Amtsgericht Dresden", federalState: "Federal state", allStates: "All states", propertyType: "Property type", allTypes: "All types", maxValue: "Market value up to", any: "Any", quickButton: "Quick search", advancedButton: "Advanced Search" },
    map: { sectionTitle: "Auctions on the map", sectionText: "A quick overview. The large map with all filters is available in the Map section.", openLargeMap: "Open large map", title: "Property map", subtitle: "Search within the visible map area or draw your own search region.", searchArea: "Search this map area", drawRegion: "Draw region", page: "Page", found: "Found", active: "Active", cancelled: "Cancelled", archive: "Archive", maxValue: "Max. value" },
    list: { title: "Top 12 current properties", subtitle: "A short selection for the homepage. Full research is available in Advanced Search.", advancedLink: "Go to advanced search", shown: "Shown", of: "of", previous: "Previous", next: "Next" },
    footer: { about: "About us", privacy: "Privacy Policy" }
  }
} as const;

export function getSiteText(locale: Locale) {
  return siteText[locale] || siteText.de;
}
